# Generated by Django 2.2.6 on 2020-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201029_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='I love learning,it is a source of inspiration', max_length=250),
        ),
    ]
