# Generated by Django 2.2.6 on 2020-10-29 08:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images/'),
        ),
    ]
