# Generated by Django 2.2.6 on 2020-10-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialproject', '0002_auto_20201029_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Published',
            field=models.BooleanField(default=False),
        ),
    ]
