# Generated by Django 2.2.6 on 2020-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialproject', '0003_auto_20201029_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='Unpublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Published',
            field=models.BooleanField(),
        ),
    ]
