# Generated by Django 2.2.6 on 2020-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialproject', '0004_auto_20201029_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='updated_date',
            new_name='mod_date',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='Author',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='authors',
            field=models.ManyToManyField(to='tutorialproject.Author'),
        ),
    ]
