# Generated by Django 2.2.6 on 2020-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialproject', '0005_auto_20201029_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
