# Generated by Django 2.2.6 on 2020-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialproject', '0006_auto_20201029_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='mod_date',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='authors',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='Author',
            field=models.CharField(default='kate', max_length=50),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
